// Code generated by protoc-gen-micro
// source: example.proto
package pb

import (
	context "context"
	api "github.com/unistack-org/micro/v3/api"
	client "github.com/unistack-org/micro/v3/client"
)

func NewPostEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		&api.Endpoint{
			Name:    "Post.FindByID",
			Path:    []string{"/api/v1/posts/{post_id}"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
	}
}

type PostClient interface {
	FindByID(ctx context.Context, req *FindByIDRequest, opts ...client.CallOption) (*FindByIDResponse, error)
}

type PostServer interface {
	FindByID(ctx context.Context, req *FindByIDRequest, rsp *FindByIDResponse) error
}
