// Code generated by protoc-gen-micro
// source: example.proto
package pb

import (
	context "context"
	v3 "github.com/unistack-org/micro-client-http/v3"
	api "github.com/unistack-org/micro/v3/api"
	client "github.com/unistack-org/micro/v3/client"
	server "github.com/unistack-org/micro/v3/server"
	http "net/http"
)

type userClient struct {
	c    client.Client
	name string
}

func NewUserClient(name string, c client.Client) UserClient {
	return &userClient{c: c, name: name}
}

func (c *userClient) FindByID(ctx context.Context, req *FindByIDRequest, opts ...client.CallOption) (*FindByIDResponse, error) {
	errmap := make(map[string]interface{}, 3)
	errmap["404"] = &Error{}
	errmap["500"] = &Error{}
	errmap["200"] = &FindByIDResponse{}
	opts = append(opts,
		v3.ErrorMap(errmap),
	)
	opts = append(opts,
		v3.Method(http.MethodGet),
		v3.Path("/api/v1/users/{user_id}"),
	)
	rsp := &FindByIDResponse{}
	err := c.c.Call(ctx, c.c.NewRequest(c.name, "User.FindByID", req), rsp, opts...)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

type userServer struct {
	UserServer
}

func (h *userServer) FindByID(ctx context.Context, req *FindByIDRequest, rsp *FindByIDResponse) error {
	return h.UserServer.FindByID(ctx, req, rsp)
}

func RegisterUserServer(s server.Server, sh UserServer, opts ...server.HandlerOption) error {
	type user interface {
		FindByID(ctx context.Context, req *FindByIDRequest, rsp *FindByIDResponse) error
	}
	type User struct {
		user
	}
	h := &userServer{sh}
	var nopts []server.HandlerOption
	for _, endpoint := range NewUserEndpoints() {
		nopts = append(nopts, api.WithEndpoint(endpoint))
	}
	return s.Handle(s.NewHandler(&User{h}, append(nopts, opts...)...))
}
