// Code generated by protoc-gen-micro
// source: example.proto
package pb

import (
	context "context"
	api "github.com/unistack-org/micro/v3/api"
	client "github.com/unistack-org/micro/v3/client"
)

func NewPostEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		&api.Endpoint{
			Name:    "Post.FindByID",
			Path:    []string{"/api/v1/posts/{post_id}"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
		&api.Endpoint{
			Name:    "Post.GetPostFileByID",
			Path:    []string{"/api/v1/posts/{post_id}/file"},
			Method:  []string{"GET"},
			Stream:  true,
			Handler: "rpc",
		},
	}
}

type PostClient interface {
	FindByID(ctx context.Context, req *FindByIDRequest, opts ...client.CallOption) (*FindByIDResponse, error)
	GetPostFileByID(ctx context.Context, req *GetPostFileRequest, opts ...client.CallOption) (Post_GetPostFileByIDClient, error)
}

type Post_GetPostFileByIDClient interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	Close() error
	Recv() (*GetPostFileResponse, error)
}

type PostServer interface {
	FindByID(ctx context.Context, req *FindByIDRequest, rsp *FindByIDResponse) error
	GetPostFileByID(ctx context.Context, req *GetPostFileRequest, stream Post_GetPostFileByIDStream) error
}

type Post_GetPostFileByIDStream interface {
	Context() context.Context
	SendMsg(msg interface{}) error
	RecvMsg(msg interface{}) error
	Close() error
	Send(msg *GetPostFileResponse) error
}
